[project]
name = "ml-tensorflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
 requires-python = ">=3.13"
dependencies = [
    "matplotlib>=3.10.6",
    "scipy>=1.16.2",
    "numpy>=2.3.3",
    "tensorflow>=2.20.0",
]

[[tool.uv.index]]
url = "http://mirrors.aliyun.com/pypi/simple/"
default = true
